<template>
  <div v-if="report" class="report-info">
    <div class="info-section">
      <div class="info-item" v-if="report.reportId">
        <span class="info-label">Report ID</span>
        <span class="info-value">{{ report.reportId }}</span>
      </div>
      
      <div class="info-item" v-if="report.generatedBy">
        <span class="info-label">Generated By</span>
        <span class="info-value">{{ report.generatedBy }}</span>
      </div>
      
      <div class="info-item" v-if="report.timestamp">
        <span class="info-label">Timestamp</span>
        <span class="info-value">
          <DateTimeFormatter :timestamp="report.timestamp" />
        </span>
      </div>
      
      <div class="info-item" v-if="toolInfo">
        <span class="info-label">Tool</span>
        <span class="info-value">{{ toolInfo }}</span>
      </div>
      
      <div class="info-item" v-if="duration !== null">
        <span class="info-label">Duration</span>
        <span class="info-value">{{ formatDuration(duration) }}</span>
      </div>
      
      <div class="info-item" v-if="report.reportFormat || report.specVersion">
        <span class="info-label">Report Format / Spec Version</span>
        <span class="info-value">{{ [report.reportFormat, report.specVersion].join(" / ") }}</span>
      </div>
      
      <!-- Additional custom fields from extra property -->
      <template v-if="report.extra">
        <div 
          class="info-item" 
          v-for="(value, key) in report.extra" 
          :key="`extra-${key}`"
        >
          <span class="info-label">{{ formatLabel(String(key)) }}</span>
          <span class="info-value">{{ formatValue(value) }}</span>
        </div>
      </template>
    </div>
  </div>
  <div v-else class="report-info-empty">
    <p>No report data available</p>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import DateTimeFormatter from '../DateTimeFormatter.vue';
import { formatDuration, formatLabel, formatValue } from '../../../helpers/formatter';
import type { Report } from 'ctrf';

const props = defineProps({
  report: {
    type: Object as () => Report,
    default: null,
    validator: (value) => {
      // Report should have at least some basic properties
      if (!value) return true; // null/undefined is acceptable (shows empty state)
      return typeof value === 'object';
    }
  }
});

// Compute tool information string
const toolInfo = computed(() => {
  if (!props.report?.results?.tool) return null;
  
  const tool = props.report.results.tool;
  const name = tool.name || '';
  const version = tool.version ? ` v${tool.version}` : '';
  
  return name + version || null;
});

// Compute duration from summary
const duration = computed(() => {
  if (!props.report?.results?.summary) return null;
  
  const summary = props.report.results.summary;
  
  // Use duration if available
  if (summary.duration !== undefined) {
    return summary.duration;
  }
  
  // Calculate from start/stop if available
  if (summary.start !== undefined && summary.stop !== undefined) {
    return summary.stop - summary.start;
  }
  
  return null;
});
</script>

<style scoped>
/* =========================
   Container
   ========================= */
.report-info {
  margin: var(--report-spacing-lg) 0;
}

.report-info-empty {
  padding: var(--report-spacing-2xl);
  text-align: center;
  background: var(--vp-c-bg-soft);
  border-radius: var(--report-card-border-radius);
  border: 1px solid var(--vp-c-divider);
  color: var(--vp-c-text-2);
}

/* =========================
   Information Section
   ========================= */
.info-section {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: var(--report-spacing-lg);
  padding: var(--report-spacing-lg);
  background: var(--vp-custom-block-info-bg);
  border-radius: var(--report-card-border-radius);
  border: 1px solid var(--vp-c-divider);
}

.info-item {
  display: flex;
  flex-direction: column;
  gap: var(--report-spacing-xs);
}

.info-label {
  font-size: var(--report-badge-font-size);
  font-weight: 900;
  color: var(--vp-c-text-3);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.info-value {
  font-size: var(--report-control-font-size);
  color: var(--vp-c-text-1);
  word-break: break-word;
}

/* =========================
   Responsive
   ========================= */
@media (max-width: 768px) {
  .info-section {
    grid-template-columns: 1fr;
  }
}
</style>
