<template>
  <div v-if="report" class="report-info">
    <div class="info-section">
      <div class="info-item" v-if="report.reportId">
        <span class="info-label">Report ID</span>
        <span class="info-value">{{ report.reportId }}</span>
      </div>
      
      <div class="info-item" v-if="report.generatedBy">
        <span class="info-label">Generated By</span>
        <span class="info-value">{{ report.generatedBy }}</span>
      </div>
      
      <div class="info-item" v-if="report.timestamp">
        <span class="info-label">Timestamp</span>
        <span class="info-value">
          <DateTimeFormatter :timestamp="report.timestamp" />
        </span>
      </div>
      
      <div class="info-item" v-if="toolInfo">
        <span class="info-label">Tool</span>
        <span class="info-value">{{ toolInfo }}</span>
      </div>
      
      <div class="info-item" v-if="duration !== null">
        <span class="info-label">Duration</span>
        <span class="info-value">{{ formatDuration(duration) }}</span>
      </div>
      
      <div class="info-item" v-if="report.reportFormat || report.specVersion">
        <span class="info-label">Report Format / Spec Version</span>
        <span class="info-value">{{ [report.reportFormat, report.specVersion].join(" / ") }}</span>
      </div>
      
      <!-- Additional custom fields from extra property -->
      <template v-if="report.extra">
        <div 
          class="info-item" 
          v-for="(value, key) in report.extra" 
          :key="`extra-${key}`"
        >
          <span class="info-label">{{ formatLabel(key) }}</span>
          <span class="info-value">{{ formatValue(value) }}</span>
        </div>
      </template>
    </div>
  </div>
  <div v-else class="report-info-empty">
    <p>No report data available</p>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import DateTimeFormatter from '../DateTimeFormatter.vue';

const props = defineProps({
  report: {
    type: Object,
    default: null,
    validator: (value) => {
      // Report should have at least some basic properties
      if (!value) return true; // null/undefined is acceptable (shows empty state)
      return typeof value === 'object';
    }
  }
});

// Compute tool information string
const toolInfo = computed(() => {
  if (!props.report?.results?.tool) return null;
  
  const tool = props.report.results.tool;
  const name = tool.name || '';
  const version = tool.version ? ` v${tool.version}` : '';
  
  return name + version || null;
});

// Compute duration from summary
const duration = computed(() => {
  if (!props.report?.results?.summary) return null;
  
  const summary = props.report.results.summary;
  
  // Use duration if available
  if (summary.duration !== undefined) {
    return summary.duration;
  }
  
  // Calculate from start/stop if available
  if (summary.start !== undefined && summary.stop !== undefined) {
    return summary.stop - summary.start;
  }
  
  return null;
});

// Format duration in milliseconds to human-readable format
const formatDuration = (ms) => {
  if (ms === null || ms === undefined) return 'N/A';
  
  if (ms < 1000) {
    return `${ms}ms`;
  }
  
  const seconds = Math.floor(ms / 1000);
  const remainingMs = ms % 1000;
  
  if (seconds < 60) {
    return remainingMs > 0 
      ? `${seconds}.${String(remainingMs).padStart(3, '0').substring(0, 2)}s`
      : `${seconds}s`;
  }
  
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  
  return `${minutes}m ${remainingSeconds}s`;
};

// Format label from camelCase or snake_case to Title Case
const formatLabel = (key) => {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .replace(/^./, (str) => str.toUpperCase())
    .trim();
};

// Format value for display
const formatValue = (value) => {
  if (value === null || value === undefined) return 'N/A';
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
};
</script>

<style scoped>
.report-info {
  margin: 1rem 0;
}

.info-section {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 1rem;
  padding: 1rem;
  background: var(--vp-custom-block-info-bg);
  border-radius: 8px;
  border: 1px solid var(--vp-c-divider);
}

.info-item {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.info-label {
  font-size: 0.75rem;
  font-weight: 900;
  color: var(--vp-c-text-3);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.info-value {
  font-size: 0.875rem;
  color: var(--vp-c-text-1);
  word-break: break-word;
}

.report-info-empty {
  padding: 2rem;
  text-align: center;
  background: var(--vp-c-bg-soft);
  border-radius: 8px;
  border: 1px solid var(--vp-c-divider);
  color: var(--vp-c-text-2);
}

/* Responsive adjustments */
@media (max-width: 768px) {
  .info-section {
    grid-template-columns: 1fr;
  }
}
</style>
