<template>
  <div v-if="props.report">
    <!-- Primary Metrics Cards -->
    <div class="relative overflow-hidden rounded-xl border transition-all border-b-4 border-[var(--vp-c-tip-soft)]">
      <div class="grid grid-cols-1 gap-1 p-2">
        <!-- Duration Card -->
        <div v-if="duration !== null" class="relative overflow-hidden rounded-xl transition-all duration-200">
          <div class="absolute top-0 right-0 opacity-[0.03]"></div>
          <div class="py-1 px-3">
            <div class="flex items-center">
              <div class="flex items-center justify-center w-10 h-10 rounded-lg">
                <ClockIcon class="w-5 h-5"/>
              </div>
              <div class="text-xs uppercase tracking-wider text-[var(--vp-c-text-3)]">Total Duration</div>
            </div>
            <div class="text-sm tabular-nums text-[var(--vp-c-brand-1)]">{{ formatDuration(duration) }}</div>
          </div>
        </div>

        <!-- Generated By Card -->
        <div v-if="props.report.generatedBy" class="relative overflow-hidden rounded-xl transition-all duration-200">
          <div class="absolute top-0 right-0 opacity-[0.03]"></div>
          <div class="py-1 px-3">
            <div class="flex items-center">
              <div class="flex items-center justify-center w-10 h-10 rounded-lg mr-1">
                <WrenchScrewdriverIcon class="w-5 h-5"/>
              </div>
              <div class="text-xs uppercase tracking-wider text-[var(--vp-c-text-3)]">Generated By</div>
            </div>
            <div class="text-sm truncate text-[var(--vp-c-text-1)]">{{ report.generatedBy }}</div>
          </div>
        </div>

        <!-- Tool Card -->
        <div v-if="toolInfo" class="relative overflow-hidden rounded-xl transition-all duration-200">
          <div class="absolute top-0 right-0 opacity-[0.03]"></div>
          <div class="py-1 px-3">
            <div class="flex items-center">
              <div class="flex items-center justify-center w-10 h-10 rounded-lg">
                <WrenchScrewdriverIcon class="w-5 h-5"/>
              </div>
              <div class="text-xs uppercase tracking-wider text-[var(--vp-c-text-3)]">Testing Tool</div>
            </div>
            <div class="text-sm truncate text-[var(--vp-c-text-1)]">{{ toolInfo }}</div>
          </div>
        </div>

        <!-- Timestamp Card -->
        <div v-if="props.report.timestamp" class="relative overflow-hidden rounded-xl transition-all duration-200">
          <div class="absolute top-0 right-0 opacity-[0.03]"></div>
          <div class="py-1 px-3">
            <div class="flex items-center">
              <div class="flex items-center justify-center w-10 h-10 rounded-lg">
                <CalendarIcon class="w-5 h-5"/>
              </div>
              <div class="text-xs uppercase tracking-wider text-[var(--vp-c-text-3)]">Executed At</div>
            </div>
            <div class="text-sm text-[var(--vp-c-text-1)]">
              <DateTimeFormatter :timestamp="report.timestamp" />
            </div>
          </div>
        </div>

        <!-- Report ID Card -->
        <div v-if="props.report.reportId" class="relative overflow-hidden rounded-xl transition-all duration-200">
          <div class="absolute top-0 right-0 opacity-[0.03]"></div>
          <div class="py-1 px-3">
            <div class="flex items-center">
              <div class="flex items-center justify-center w-10 h-10 rounded-lg">
                <FingerPrintIcon class="w-5 h-5"/>
              </div>
              <div class="text-xs uppercase tracking-wider text-[var(--vp-c-text-3)]">Report ID</div>
            </div>
            <div class="text-xs truncate text-[var(--vp-c-text-1)]">{{ report.reportId }}</div>
          </div>
        </div>

        <!-- Report Format and Spec Version Card -->
        <div v-if="props.report.reportFormat || props.report.specVersion" class="relative overflow-hidden rounded-xl transition-all duration-200">
          <div class="absolute top-0 right-0 opacity-[0.03]"></div>
          <div class="py-1 px-3">
            <div class="flex items-center">
              <div class="flex items-center justify-center w-10 h-10 rounded-lg">
                <DocumentTextIcon class="w-5 h-5"/>
              </div>
              <div class="text-xs uppercase tracking-wider text-[var(--vp-c-text-3)]">Format / Version</div>
            </div>
            <div class="text-xs truncate text-[var(--vp-c-text-1)]">{{ [report.reportFormat, report.specVersion].filter(Boolean).join(" / ") }}</div>
          </div>
        </div>
      </div>
    </div>

    <!-- Secondary Information Panel -->
    <div v-if="props.report.extra" class="rounded-xl border bg-[var(--vp-c-bg-soft)] border-[var(--vp-c-divider)]">
      <div class="px-5 py-4 border-b border-[var(--vp-c-divider)]">
        <h4 class="text-sm font-bold tracking-tight text-[var(--vp-c-text-1)]">Additional Metadata</h4>
      </div>
      <div class="p-5">
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <!-- Additional custom fields from extra property -->
          <template v-if="props.report.extra">
            <div
              v-for="(value, key) in props.report.extra"
              :key="`extra-${key}`"
            >
              <p class="text-xs font-semibold uppercase tracking-wider text-[var(--vp-c-text-3)]">{{ formatLabel(String(key)) }}</p>
              <p class="px-3 py-2 text-sm font-medium break-words rounded-lg text-[var(--vp-c-text-1)] bg-[var(--vp-c-default-soft)]">{{ formatValue(value) }}</p>
            </div>
          </template>
        </div>
      </div>
    </div>
  </div>
  <div v-else class="flex flex-col items-center justify-center p-12 rounded-xl border-2 border-dashed bg-[var(--vp-c-bg-soft)] border-[var(--vp-c-divider)]">
    <svg class="w-12 h-12 mb-3 text-[var(--vp-c-text-3)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
    </svg>
    <p class="text-sm font-medium text-[var(--vp-c-text-3)]">No report data available</p>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import DateTimeFormatter from '../../components/DateTimeFormatter.vue';
import { formatDuration, formatLabel, formatValue } from '../../../helpers/formatter';
import { ClockIcon, CalendarIcon, DocumentTextIcon, WrenchScrewdriverIcon, FingerPrintIcon } from '@heroicons/vue/16/solid';
import type { Report } from 'ctrf';

const props = defineProps({
  report: {
    type: Object as () => Report,
    required: false,
    default: null,
  },
});

// Compute tool information string
const toolInfo = computed(() => {
  if (!props.report?.results?.tool) return null;

  const tool = props.report.results.tool;
  const name = tool.name;
  const version = tool.version ? ` v${tool.version}` : '';

  return name + version || null;
});

// Compute duration from summary
const duration = computed(() => {
  if (!props.report?.results?.summary) return null;

  const summary = props.report.results.summary;
  
  // Use duration if available
  if (summary.duration !== undefined) {
    return summary.duration;
  }
  
  // Calculate from start/stop if available
  if (summary.start !== undefined && summary.stop !== undefined) {
    let start = summary.start;
    let stop = summary.stop;
    
    // Convert to milliseconds if values are in seconds (Unix timestamp)
    // Unix timestamps in seconds are typically 10 digits (e.g., 1700000000)
    // Unix timestamps in milliseconds are typically 13 digits (e.g., 1700000000000)
    if (start < 10000000000) {
      start = start * 1000;
    }
    if (stop < 10000000000) {
      stop = stop * 1000;
    }
    
    return stop - start;
  }
  
  return null;
});
</script>

